In [8]:
arr = [ [1, 2, 3],
[4, 5, 6],
[7, 8, 9] ]

for i in arr:
    for j in i:
        print(j + 5)


6
7
8
9
10
11
12
13
14


In [9]:
import numpy as np

In [10]:
arr = np.array(arr)
arr += 5
print(arr)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [11]:
matrix = [['A', 'B', 'C', 'D'], ['E', 'F', 'G', 'H'], ['I', 'J', 'K', 'L'], ['M', 'N', 'O', 'P']]

In [15]:
matrix = np.array(matrix)
print(matrix)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']
 ['I' 'J' 'K' 'L']
 ['M' 'N' 'O' 'P']]


In [16]:
matrix.diagonal()

array(['A', 'F', 'K', 'P'], dtype='<U1')

In [19]:
# fliplr() : flip left to right
print(np.fliplr(matrix))
print(np.fliplr(matrix).diagonal())

[['D' 'C' 'B' 'A']
 ['H' 'G' 'F' 'E']
 ['L' 'K' 'J' 'I']
 ['P' 'O' 'N' 'M']]
['D' 'G' 'J' 'M']


In [24]:
m = [[1, 2, 3], [4, 5, 6],[7, 8, 9]]

In [22]:
np.triu(m)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [23]:
np.tril(m)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])